apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredge-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sourabhdey21/coredge-deploy.git
    path: applicationsets/demo
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
