apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ce-demo-frontend
  namespace: argocd
  labels:
    customer: coredge
    env: demo
    category: frontend
spec: 
  generators:
    - list:
        elements:
          - app: admin-portal
          #- app: celery-flower
          - app: user-portal
          - app: mongo-express
          - app: pgadmin
  template: 
    metadata: 
      name: '{{app}}-ce-demo'
      namespace: argocd
      labels:
        customer: coredge
        env: demo
        category: frontend
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: ce-demo
      # values repo first so it shows in argocd UI
      sources:
        - repoURL: https://github.com/coredgeio/coredge-deploy-repo.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/coredgeio/ccs-helm-charts.git
          targetRevision: main
          path: helm/frontend-charts/{{app}}
          helm:
            valueFiles:
              - $values/demo/images.yaml
              - $values/demo/frontend/{{app}}/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
