apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluid-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sourabhdey21/coredge-deploy.git
    targetRevision: master        # Branch for your target environment
    path: applicationsets/dev   # Change to: applicationsets/qa, /prod, or /demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
