mode: standalone

replicas: 1

rootUser: admin
rootPassword: password123

persistence:
  enabled: true
  size: 20Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

# MinIO API Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  path: /
  hosts:
    - minio-api.coredge.internal
  tls:
    - secretName: coredge-tls
      hosts:
        - minio-api.coredge.internal

# MinIO Console Ingress
consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  path: /
  hosts:
    - minio-console.coredge.internal
  tls:
    - secretName: coredge-tls
      hosts:
        - minio-console.coredge.internal

affinity: {}

podDisruptionBudget:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9000"
