# compass-orchestrator - airtel dev
# copied from ccs-helm-charts

replicaCount:
  compassOrchestrator: 1

global:
  repository: coredgeio
  imagePullPolicy: Always
  releaseTag: latest
  UseDailyBuilds: false

  rootRealm: "cloud"
  dnsEnabled: false

  keycloak:
    domain: ""

  proxy:
    enabled: false
    http_proxy: ""

  mongodb:
    external:
      enabled: false
      configdb:
        host: ""
        port: ""
      metricsdb:
        host: ""
        port: ""
    globaldb:
      host: ""
      port: ""

betaFeatures:
  enabled: false

orchestrator:
  helmRepos: []
