# admin-platform - core42 dev
# copied from ccs-helm-charts

global:
  # indicates enabling use of DNS hostnames via Ingress
  # switch to indicate use of domain configuration
  dnsEnabled: &dnsEnabled false

  # Type to expose UI services with
  # Supported: ingress / loadbalancer
  serviceExposure:
    type: "ingress"

  # Ingress claas to be defined to inngress configuration when using Ingress controller
  # Only used when supports Nginx Ingress Controller
  # Only used when global.serviceExposure.type==ingress
  ingressClass: &ingressClass "nginx"

  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # this field is considered only when UseDailyBuilds is set to be false
  # provides configuration of build tag to be used for container images
  releaseTag: &releaseTag latest

  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

  # external IP for controller, relevant, when domain is not
  # configured to allow generation of server certificate validity using
  # this IP address
  externalIP: &controllerIP 127.0.0.1

  # Flask Config (Development OR Production)
  # TEMPORARY
  flaskConfig: "development"

  # keycloak realm to be used as the root
  rootRealm: &rootRealm "cloud"

  ## Keycloak Architecture override to enable HA or standalone
#  keycloak:
#    domain: &keycloakDomain ""
#    nodePorts:
#      http: &keycloakNodePortHTTP "32701"
#      https: &keycloakNodePortHTTPS "32702"

  # Default application type: "ccp"
  application: "ccp"
  projectLabel: "" # value could be "Cell" in Airtel otherwise is null

  events:
    enabled: false
  
    # CMP portal, to create service request eg: JIRA, serviceNow
  orbiterTicketingService:
    enabled: false
  ## NEED  TO CHECK WITH RAKESH ONCE THAT HELPER FILE IS REQUIRED OR NOT
  ## Override for PostgresDB architecture
  ## global.postgresql.architecture.standalone Set to 'false' deploys a postgresql as a cluster with High Availability
  ## global.postgresql.architecture.standalone Set to 'true' deploys postgresql in standalone mode with no High Availability
#  postgresql:
#    architecture:
#      standalone: false
#    ### Config overrride to use external Postgres
#    ### This will not deploy postgresql with ccp
#    external:
#      host: ""
#      port: ""
#      user: ""
#      database: ""
#      password: ""

#  mongodb:
#    external:
#      enabled: false
#      configdb:
#        host: ""
#        port: ""
#        user: ""
#        pass: ""
#      metricsdb:
#        host: ""
#        port: ""
#        user: ""
#        pass: ""
#    globaldb:
#      host: ""
#      port: ""
#      user: ""
#      pass: ""
#
#  ## Config override for AuditDB Postgres server details
#  auditdb:
#    host: ''
#    port: ''
#    database: ''
#    username: ''
#    password: ''
#
#  redisdb:
#    host: ""
#    port: ""
#    pass: ""
#    tlsEnabled: false

  #Set this to true for environments without internet and update the proxy details
  proxy:
    enabled: false
    http_proxy: ""
    https_proxy: ""
    no_proxy: "localhost,127.0.0.1,cluster.local,.svc,.svc.cluster.local"

  ## Configuration for exposing frontend URLs
  ## DNS hostnames considered only when global.dnsEnabled is 'true'
  ## Othwerwise NodePorts considered
#  frontend:
#    admin:
#      domain: &adminDomain ""
#      tlsSecret: &adminTls ""
#    userPortal:
#      domain: &userDomain ""
#      tlsSecret: &userTls ""
#      nodePort: &frontendNodePort "32500"


nodeSelector: {} 

replicaCount: 1

allowedAdminUserDomain: ""

adminportal:
  image: "fluid-admin"
  service:
    nodePort: "32600"
  resources: 
    limits:
      cpu: 400m
      # memory: 128Mi
    requests:
      cpu: 100m
      memory: 200Mi
  ## Only use when https.enabled is set true
  ## Else leave empty
  ingress:
    tlsSecret: ""
    hostname: ""
  ## Monitoring URLs
  monitoringURL: 
    resource: ""
    projectResource: ""
  ## Management URLs
  managementURL: 
    resource: ""
  ## Enabled Services
  enabledServices: ""

adminPlatform:
  image: "fluid_admin_platform"
  resources: 
    limits:
      cpu: 500m
      # memory: 128Mi
    requests:
      cpu: 100m
      memory: 200Mi
  celery:
    enabled: true
    replicaCount: 1
    command: >
      celery -A app.celery worker
      --loglevel=INFO
      --concurrency=1
      --prefetch-multiplier=1
    resources: 
      limits:
        cpu: 1000m
        memory: 8Gi    
      requests:
        cpu: 100m
        memory: 4Gi    
  
