# keycloak-ha - airtel qa
# copied from ccs-helm-charts

## Global Container image registry
## Global Container image repository
## Global Container image Release tag
## Global Container image Pull Policy
## Global Container image Pull Secrets
## Global Storage Class for persistent volumes
global:
  registry: &registry docker.io
  repository: &repository coredgeio
  imagePullPolicy: &imagePolicy Always
  imagePullSecrets: []
  storageClass: &storageClass ""

## Keycloak replica count.
## Minimum is set to 3 to provide HA capabilities
replicaCount: 1

## Keycloak Image and Tag
image:
  name: keycloak
  tag: "v24.0.5-coredgev3"

## Full Name Override for all resources in the helm chart
# fullnameOverride: ""

## Keycloak authentication parameters. Password change recommended
## If using external postgresql, make sure admin user and password are consistent
auth:
  ### Keycloak administrator user
  adminUser: "admin"
  ### Keycloak administrator password
  adminPass: "admin"

## Keycloak service overrides
## Default is set to ClusterIP
service:
  type: NodePort
  nodePorts:
    # overridden (placeholders replacing your YAML aliases)
    http: "32705"
    https: "32706"

## Set Keycloak Themes
themeOverride:
  enabled: false
  default: ""
  welcome: ""
  admin: ""

## Set container requests and limits for different resources like CPU or memory (essential for production workloads)
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

## Name of the secret containing the Keycloak custom CA certificates. The secret will be mounted as a directory and configured using KC_TRUSTSTORE_PATHS.
## https://www.keycloak.org/server/keycloak-truststore
## Could be created like this: kubectl create secret generic secretName --from-file=./certificateToMerge.pem
customCaExistingSecret: ""

## HTTPS settings
tls:
  ### Enable TLS encryption. Required to enable HTTPs traffic.
  enabled: true
  ### Uses generated self signed tls certs in PEM format.
  selfSigned: true
  ### Existing secret containing the TLS certificates per Keycloak replica
  ### If using PEM, make sure the PEM key and cert are named 'tls.key' and 'tls.crt' respectively.
  ### Make sure tls.selfSigned == false
  tlsSecretName: ""

## Run Keycloak in production mode.
## TLS configuration is required except when using proxy=edge.
production: true

## Proxy mode edge, reencrypt, passthrough or none
proxy: edge

# hostname: "auth-qa.coredge.internal"

## Set the path relative to '/' for serving resources.
## Useful if you are migrating from older version which were using '/auth/'
httpRelativePath: "/auth/"

## Extra Keycloak Configuration overrides that are required for tunining/configuration when Keycloak is running in high load environments
## configuration.database.poolSize.initial The initial size of the connection pool
## configuration.database.poolSize.minimum The minimal size of the connection pool
## configuration.database.poolSize.maximum The maximum size of the connection pool. Should always be less than the postgresql max allowed connections
extraConfiguration:
  database:
    poolSize:
      initial: "10"
      minimum: "20"
      maximum: "100"

## Keycloak ingress parameters. (User facing)
ingress:
  enabled: true
  className: "nginx"
  extraAnnotations: {}
  hostname: "auth-qa.coredge.internal"
  tlsSecret: "coredge-tls"

## Keycloak admin ingress parameters
adminIngress:
  enabled: "true"     # overridden (placeholder replacing your YAML alias)
  className: "nginx" # overridden (placeholder replacing your YAML alias)
  extraAnnotations: {}
  hostname: "auth-qa.coredge.internal" # overridden (placeholder replacing your YAML alias)
  tlsSecret: "coredge-tls"   # overridden (placeholder replacing your YAML alias)

## Keycloak logging configuration.
## Alternates between the default log output format or json format
## Available options : FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL, OFF. Default is INFO
logging:
  output: default
  level: INFO

## Keycloak HPA autoscaling configuration
## Requires a metrics server pre-installed
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes for keycloak
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts for keycloak
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

## Override Command
command: []

nodeSelector: {}

tolerations: []

## Enable affinity for Keycloak Pods/Members
## Below example will schedule each keycloak replica on distinct k8s nodes
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - keycloak
  #     topologyKey: "kubernetes.io/hostname"


## Use external Postgresql configuration.
## Above Postgresql cluster configuration will be ignored
externalPostgresql:
  host: ""
  port: ""
  user: ""
  database: ""
  password: ""


## Postgresql Operator configuration
## This operator will manage the lifecycl of the above postgresql cluster
postgres-operator:
  enabled: false  

## Postgresql HA cluster Configuration
pgcluster:
  ## Postgresql cluster name prefix
  name: "keycloak"
