# compass-term - coredge prod
# copied from ccs-helm-charts

replicaCount:
  compassTerminal: 1

global:
  repository: coredgeio
  imagePullPolicy: Always
  releaseTag: latest

  dnsEnabled: false

  frontend:
    userPortal:
      domain: ""
      nodePort: "32500"

  mongodb:
    external:
      enabled: false
      configdb:
        host: ""
        port: ""
      metricsdb:
        host: ""
        port: ""
    globaldb:
      host: ""
      port: ""

controller:
  externalIP: "127.0.0.1"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# HPA Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80