apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backup-crons-qa
  namespace: argocd
  labels:
    customer: ccs
    env: qa
    category: backup-crons
spec:
  generators:
    - list:
        elements:
          - app: keycloak-postgres
          - app: ccs-postgres
          - app: mongodb
          - app: openfga
          #- app: etcd
  template:
    metadata:
      name: '{{app}}-backup-cron-qa'
      namespace: argocd
      labels:
        customer: ccs
        env: qa
        category: backup-crons
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: coredge-qa
      sources:
        # 1) values repo
        - repoURL: https://github.com/sourabhdey21/coredge-deploy.git
          targetRevision: main
          ref: values
        # 2) helm charts repo
        - repoURL: https://github.com/sourabhdey21/ccs-helm-charts.git
          targetRevision: main
          path: helm/backup-crons/{{app}}
          helm:
            valueFiles:
              - $values/qa/backup-crons/{{app}}/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
