apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    category: backend
    customer: coredge
    env: prod
  name: coredge-prod-backend
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: admin-platform-celery
      - app: admin-platform
      #- app: archival-storage
      - app: auth-service
      - app: autoscaling
      - app: backup-service
      - app: baremetal-manager
      - app: ccp-extension
      #- app: certificates-manager
      - app: cloud-manager
      - app: compass-api
      - app: compass-cluster-manager
      - app: compass-controller
      - app: compass-image-scanner
      - app: compass-metric-server
      - app: compass-multicloud-manager
      - app: compass-orchestrator
      - app: compass-term
      - app: compute-service
      - app: container-registry
      - app: core-mgmt-service
      - app: fluid-monitoring-service
      - app: helper
      - app: kg-cluster-notifier
      - app: metering
      - app: network-manager
      - app: neutron-service
      #- app: notification-service
      - app: orbiter-ticketing-service
      - app: gpu-paas-user
      - app: gpu-paas-comm
      - app: sockets-server
      - app: storage-plugin
      - app: tenant-management-service
      - app: vmconsole
      - app: volume-service
      - app: workflow-manager
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        category: backend
        customer: coredge
        env: prod
      name: '{{app}}-coredge-prod'
      namespace: argocd
    spec:
      destination:
        namespace: coredge-prod
        server: https://kubernetes.default.svc
      project: default
      sources:
      - ref: values
        repoURL: https://github.com/sourabhdey21/coredge-deploy.git
        targetRevision: master
      - helm:
          valueFiles:
          - $values/prod/images.yaml
          - $values/prod/backend/{{app}}/values.yaml
        path: helm/backend-charts/{{app}}
        repoURL: https://github.com/sourabhdey21/ccs-helm-charts.git
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
