# cloud-manager - core42 dev
# copied from ccs-helm-charts

global:
  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

  mongodb:
    external:
      enabled: false
      configdb:
        host: ""
        port: ""
        user: ""
        pass: ""
      metricsdb:
        host: ""
        port: ""
        user: ""
        pass: ""
    globaldb:
      host: ""
      port: ""
      user: ""
      pass: ""

replicaCount:
  cloudManager: 0
