# notification-service - coredge demo
# copied from ccs-helm-charts

global:
  smtp:
    enabled: true      
    senderEmail: "noreply@DFlare.com"
    senderName: "DFlare Admin"      
    smtpHost: "smtp.dummy.com"
    smtpPort: 25
    authRequired: true       
    username: "username"     
    password: "password"

  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # this field is considered only when UseDailyBuilds is set to be false
  # provides configuration of build tag to be used for container images
  releaseTag: &releaseTag latest
  
  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

replicaCount: 1

image: "fluid_notification"

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 50Mi
nodeSelector: {}  

command: []

smtp:
  senderEmail: ''
  server: ''
  port: ''
  username: ''
  password: ''

sms:
  sender: ''
  apiKey: ''

# HPA Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
