# cloud-manager - coredge prod
# copied from ccs-helm-charts

global:
  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

  mongodb:
    external:
      enabled: false
      configdb:
        host: ""
        port: ""
        user: ""
        pass: ""
      metricsdb:
        host: ""
        port: ""
        user: ""
        pass: ""
    globaldb:
      host: ""
      port: ""
      user: ""
      pass: ""

replicaCount:
  cloudManager: 1

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# HPA Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80