# sockets-server - coredge prod
# copied from ccs-helm-charts

global:
  repository: coredgeio
  imagePullPolicy: Always
  releaseTag: latest

sockets:
  replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# HPA Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80