apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orange-dev-backend
  namespace: argocd
  labels:
    customer: orange
    env: dev
    category: backend
spec: 
  generators:
    - list:
        elements:
          - app: admin-platform-celery
          - app: admin-platform
          - app: auth-service
          - app: ccp-extension
          - app: compass-api
          - app: compass-cluster-manager
          - app: compass-controller
          - app: compass-metric-server
          - app: compass-orchestrator
          - app: compass-term
          - app: compute-service
          - app: container-registry
          - app: core-mgmt-service
          # - app: helper
          - app: kg-cluster-notifier
          - app: metering
          - app: network-manager
          - app: neutron-service
          # - app: notification-service
          - app: orbiter-ticketing-service
          - app: repository-cred
          - app: sockets-server
          - app: storage-plugin
          - app: tenant-management-service
          - app: vmconsole
          - app: volume-service
          - app: gpu-paas-user
          - app: gpu-paas-comm
          # - app: workflow-manager
  template: 
    metadata: 
      name: '{{app}}-orange-dev'
      namespace: argocd
      labels:
        customer: orange
        env: dev
        category: backend
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: orange-dev
      # values repo first so it shows in argocd UI
      sources:
        - repoURL: https://github.com/coredgeio/coredge-deploy-repo.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/coredgeio/ccs-helm-charts.git
          targetRevision: main
          path: helm/backend-charts/{{app}}
          helm:
            valueFiles:
              - $values/orange/images.yaml
              - $values/orange/backend/{{app}}/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
