# autoscaling - airtel dev
# copied from ccs-helm-charts

global:
  # indicates usage of external ingress, currently also acts as a
  # switch to indicate use of domain configuration
  dnsEnabled: &dnsEnabled false

  # Ingress claas to be defined to Ingress configuration 
  ingressClass: &ingressClass ""

  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # this field is considered only when UseDailyBuilds is set to be false
  # provides configuration of build tag to be used for container images
  releaseTag: &releaseTag latest

  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

  # external IP for controller, relevant, when domain is not
  # configured to allow generation of server certificate validity using
  # this IP address
  externalIP: &controllerIP 127.0.0.1

  # Flask Config (Development OR Production)
  # TEMPORARY
  flaskConfig: "production"

  events:
    enabled: false

nodeSelector: {} 

replicaCount: 1

image: "fluid_platform"

resources: 
  limits:
    cpu: 400m
    # memory: 128Mi
  requests:
    cpu: 100m
    memory: 200Mi

celery:
  enabled: true
  replicaCount: 1
  command: "celery -A app  worker --concurrency=2 --loglevel=debug -Q q_autoscaling_group"
  resources: 
    limits:
      cpu: 1000m
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 2Gi

enabledServices: "autoscaling_group,api"

autoscalingEnv:
  # heatAsgEventBaseUrl: "http://100.65.246.198:32139"
  autoscalingApiUrl: "http://autoscaling-service:7181"
  grafana:
    url: "https://10.81.60.100:3000"
    alertRuleFolderId: "afbjp3wb1zu2od"
    username: "admin"
    password: "LpbNxa9hzCCkjx34W7k0EYmNKhKD77KCOjbW7AlT"
    notificationPolicyLabel: "app"
    notificationPolicyType: "ccp-dev"
    cpuloadquery: '(sum(irate(libvirt_domain_info_cpu_time_seconds_total{uuid=~".*[instance_id].*"}[5m])) / 1000000000 / [total_vcpus]) * 100'
