# Prod overrides for `coredge-monitoring/helm/prometheus-node-exporter` chart.
# Defaults live in `coredge-monitoring/helm/prometheus-node-exporter/values.yaml`.

fullnameOverride: node-exporter

image:
  registry: docker.io
  repository: coredgeio/node-exporter
  tag: "v1.7.0"
  pullPolicy: IfNotPresent
  digest: ""

revisionHistoryLimit: 20

resources: {}

service:
  enabled: true
  type: ClusterIP
  port: 9100
  targetPort: 9100
