global:
  victoriaLogs:
    enabled: true
  vmauth:
    enabled: true
  imagePullSecrets: []
  image:
    registry: ""
  compatibility:
    openshift:
      adaptSecurityContext: "auto"
  cluster:
    dnsDomain: cluster.local.

vlselect:
  enabled: true
  name: ""
  image:
    registry: ""
    repository: docker.io/coredgeio/victoria-logs
    tag: ""
    variant: ""
    pullPolicy: IfNotPresent
  ports:
    name: "http"
  priorityClassName: ""
  fullnameOverride: "vlselect"

vlinsert:
  enabled: true
  name: ""
  image:
    registry: ""
    repository: docker.io/coredgeio/victoria-logs
    tag: ""
    variant: ""
    pullPolicy: IfNotPresent
  ports:
    name: "http"
  priorityClassName: ""
  fullnameOverride: "vlinsert"

vlstorage:
  enabled: true
  name: ""
  image:
    registry: ""
    repository: docker.io/coredgeio/victoria-logs
    tag: ""
    variant: ""
    pullPolicy: IfNotPresent
  ports:
    name: "http"
  priorityClassName: ""
  fullnameOverride: "vlstorage"
  retentionPeriod: "30d"
